/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-12 at 03:31:22 UTC 
 * Modify at your own risk.
 */

package com.urlisit.siteswrapper.cloud.model.pageendpoint;

/**
 * Service definition for Pageendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PageendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pageendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the pageendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://towingenterpriseexecutive.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pageendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pageendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pageendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPage".
   *
   * This request holds the parameters needed by the pageendpoint server.  After setting any optional
   * parameters, call the {@link GetPage#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPage getPage(java.lang.Long id) throws java.io.IOException {
    GetPage result = new GetPage(id);
    initialize(result);
    return result;
  }

  public class GetPage extends PageendpointRequest<com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page> {

    private static final String REST_PATH = "page/{id}";

    /**
     * Create a request for the method "getPage".
     *
     * This request holds the parameters needed by the the pageendpoint server.  After setting any
     * optional parameters, call the {@link GetPage#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetPage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPage(java.lang.Long id) {
      super(Pageendpoint.this, "GET", REST_PATH, null, com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPage setAlt(java.lang.String alt) {
      return (GetPage) super.setAlt(alt);
    }

    @Override
    public GetPage setFields(java.lang.String fields) {
      return (GetPage) super.setFields(fields);
    }

    @Override
    public GetPage setKey(java.lang.String key) {
      return (GetPage) super.setKey(key);
    }

    @Override
    public GetPage setOauthToken(java.lang.String oauthToken) {
      return (GetPage) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPage setQuotaUser(java.lang.String quotaUser) {
      return (GetPage) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPage setUserIp(java.lang.String userIp) {
      return (GetPage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPage set(String parameterName, Object value) {
      return (GetPage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPage".
   *
   * This request holds the parameters needed by the pageendpoint server.  After setting any optional
   * parameters, call the {@link InsertPage#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page}
   * @return the request
   */
  public InsertPage insertPage(com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page content) throws java.io.IOException {
    InsertPage result = new InsertPage(content);
    initialize(result);
    return result;
  }

  public class InsertPage extends PageendpointRequest<com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page> {

    private static final String REST_PATH = "page";

    /**
     * Create a request for the method "insertPage".
     *
     * This request holds the parameters needed by the the pageendpoint server.  After setting any
     * optional parameters, call the {@link InsertPage#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page}
     * @since 1.13
     */
    protected InsertPage(com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page content) {
      super(Pageendpoint.this, "POST", REST_PATH, content, com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page.class);
    }

    @Override
    public InsertPage setAlt(java.lang.String alt) {
      return (InsertPage) super.setAlt(alt);
    }

    @Override
    public InsertPage setFields(java.lang.String fields) {
      return (InsertPage) super.setFields(fields);
    }

    @Override
    public InsertPage setKey(java.lang.String key) {
      return (InsertPage) super.setKey(key);
    }

    @Override
    public InsertPage setOauthToken(java.lang.String oauthToken) {
      return (InsertPage) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPage setQuotaUser(java.lang.String quotaUser) {
      return (InsertPage) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPage setUserIp(java.lang.String userIp) {
      return (InsertPage) super.setUserIp(userIp);
    }

    @Override
    public InsertPage set(String parameterName, Object value) {
      return (InsertPage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPage".
   *
   * This request holds the parameters needed by the pageendpoint server.  After setting any optional
   * parameters, call the {@link ListPage#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListPage listPage() throws java.io.IOException {
    ListPage result = new ListPage();
    initialize(result);
    return result;
  }

  public class ListPage extends PageendpointRequest<com.urlisit.siteswrapper.cloud.model.pageendpoint.model.CollectionResponsePage> {

    private static final String REST_PATH = "page";

    /**
     * Create a request for the method "listPage".
     *
     * This request holds the parameters needed by the the pageendpoint server.  After setting any
     * optional parameters, call the {@link ListPage#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListPage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPage() {
      super(Pageendpoint.this, "GET", REST_PATH, null, com.urlisit.siteswrapper.cloud.model.pageendpoint.model.CollectionResponsePage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPage setAlt(java.lang.String alt) {
      return (ListPage) super.setAlt(alt);
    }

    @Override
    public ListPage setFields(java.lang.String fields) {
      return (ListPage) super.setFields(fields);
    }

    @Override
    public ListPage setKey(java.lang.String key) {
      return (ListPage) super.setKey(key);
    }

    @Override
    public ListPage setOauthToken(java.lang.String oauthToken) {
      return (ListPage) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPage setQuotaUser(java.lang.String quotaUser) {
      return (ListPage) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPage setUserIp(java.lang.String userIp) {
      return (ListPage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPage setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPage setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPage set(String parameterName, Object value) {
      return (ListPage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePage".
   *
   * This request holds the parameters needed by the pageendpoint server.  After setting any optional
   * parameters, call the {@link RemovePage#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemovePage removePage(java.lang.Long id) throws java.io.IOException {
    RemovePage result = new RemovePage(id);
    initialize(result);
    return result;
  }

  public class RemovePage extends PageendpointRequest<Void> {

    private static final String REST_PATH = "page/{id}";

    /**
     * Create a request for the method "removePage".
     *
     * This request holds the parameters needed by the the pageendpoint server.  After setting any
     * optional parameters, call the {@link RemovePage#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePage(java.lang.Long id) {
      super(Pageendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePage setAlt(java.lang.String alt) {
      return (RemovePage) super.setAlt(alt);
    }

    @Override
    public RemovePage setFields(java.lang.String fields) {
      return (RemovePage) super.setFields(fields);
    }

    @Override
    public RemovePage setKey(java.lang.String key) {
      return (RemovePage) super.setKey(key);
    }

    @Override
    public RemovePage setOauthToken(java.lang.String oauthToken) {
      return (RemovePage) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePage setQuotaUser(java.lang.String quotaUser) {
      return (RemovePage) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePage setUserIp(java.lang.String userIp) {
      return (RemovePage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePage set(String parameterName, Object value) {
      return (RemovePage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePage".
   *
   * This request holds the parameters needed by the pageendpoint server.  After setting any optional
   * parameters, call the {@link UpdatePage#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page}
   * @return the request
   */
  public UpdatePage updatePage(com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page content) throws java.io.IOException {
    UpdatePage result = new UpdatePage(content);
    initialize(result);
    return result;
  }

  public class UpdatePage extends PageendpointRequest<com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page> {

    private static final String REST_PATH = "page";

    /**
     * Create a request for the method "updatePage".
     *
     * This request holds the parameters needed by the the pageendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePage#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page}
     * @since 1.13
     */
    protected UpdatePage(com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page content) {
      super(Pageendpoint.this, "PUT", REST_PATH, content, com.urlisit.siteswrapper.cloud.model.pageendpoint.model.Page.class);
    }

    @Override
    public UpdatePage setAlt(java.lang.String alt) {
      return (UpdatePage) super.setAlt(alt);
    }

    @Override
    public UpdatePage setFields(java.lang.String fields) {
      return (UpdatePage) super.setFields(fields);
    }

    @Override
    public UpdatePage setKey(java.lang.String key) {
      return (UpdatePage) super.setKey(key);
    }

    @Override
    public UpdatePage setOauthToken(java.lang.String oauthToken) {
      return (UpdatePage) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePage setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePage) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePage setUserIp(java.lang.String userIp) {
      return (UpdatePage) super.setUserIp(userIp);
    }

    @Override
    public UpdatePage set(String parameterName, Object value) {
      return (UpdatePage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pageendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pageendpoint}. */
    @Override
    public Pageendpoint build() {
      return new Pageendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PageendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPageendpointRequestInitializer(
        PageendpointRequestInitializer pageendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pageendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
