/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-12 at 21:24:17 UTC 
 * Modify at your own risk.
 */

package com.urlisit.siteswrapper.cloud.model.siteendpoint.model;

/**
 * Model definition for Site.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the siteendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Site extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String appleTouchIconUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String applicationId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String defaultPage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayLogoAs;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean empty;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Object encodedKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String faviconUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String googleAppEngineApplication;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String googleAppEngineVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String googleWebFontsUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gwtRpcErrorMessage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoHtml;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoImage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lookAndFeel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String revision;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String revisionHistoryEnabled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String siteFooter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String siteName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Style style;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tag;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String theme;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAppleTouchIconUrl() {
    return appleTouchIconUrl;
  }

  /**
   * @param appleTouchIconUrl appleTouchIconUrl or {@code null} for none
   */
  public Site setAppleTouchIconUrl(java.lang.String appleTouchIconUrl) {
    this.appleTouchIconUrl = appleTouchIconUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApplicationId() {
    return applicationId;
  }

  /**
   * @param applicationId applicationId or {@code null} for none
   */
  public Site setApplicationId(java.lang.String applicationId) {
    this.applicationId = applicationId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDefaultPage() {
    return defaultPage;
  }

  /**
   * @param defaultPage defaultPage or {@code null} for none
   */
  public Site setDefaultPage(java.lang.String defaultPage) {
    this.defaultPage = defaultPage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Site setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayLogoAs() {
    return displayLogoAs;
  }

  /**
   * @param displayLogoAs displayLogoAs or {@code null} for none
   */
  public Site setDisplayLogoAs(java.lang.String displayLogoAs) {
    this.displayLogoAs = displayLogoAs;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEmpty() {
    return empty;
  }

  /**
   * @param empty empty or {@code null} for none
   */
  public Site setEmpty(java.lang.Boolean empty) {
    this.empty = empty;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Object getEncodedKey() {
    return encodedKey;
  }

  /**
   * @param encodedKey encodedKey or {@code null} for none
   */
  public Site setEncodedKey(java.lang.Object encodedKey) {
    this.encodedKey = encodedKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFaviconUrl() {
    return faviconUrl;
  }

  /**
   * @param faviconUrl faviconUrl or {@code null} for none
   */
  public Site setFaviconUrl(java.lang.String faviconUrl) {
    this.faviconUrl = faviconUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGoogleAppEngineApplication() {
    return googleAppEngineApplication;
  }

  /**
   * @param googleAppEngineApplication googleAppEngineApplication or {@code null} for none
   */
  public Site setGoogleAppEngineApplication(java.lang.String googleAppEngineApplication) {
    this.googleAppEngineApplication = googleAppEngineApplication;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGoogleAppEngineVersion() {
    return googleAppEngineVersion;
  }

  /**
   * @param googleAppEngineVersion googleAppEngineVersion or {@code null} for none
   */
  public Site setGoogleAppEngineVersion(java.lang.String googleAppEngineVersion) {
    this.googleAppEngineVersion = googleAppEngineVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGoogleWebFontsUrl() {
    return googleWebFontsUrl;
  }

  /**
   * @param googleWebFontsUrl googleWebFontsUrl or {@code null} for none
   */
  public Site setGoogleWebFontsUrl(java.lang.String googleWebFontsUrl) {
    this.googleWebFontsUrl = googleWebFontsUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGwtRpcErrorMessage() {
    return gwtRpcErrorMessage;
  }

  /**
   * @param gwtRpcErrorMessage gwtRpcErrorMessage or {@code null} for none
   */
  public Site setGwtRpcErrorMessage(java.lang.String gwtRpcErrorMessage) {
    this.gwtRpcErrorMessage = gwtRpcErrorMessage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoHtml() {
    return logoHtml;
  }

  /**
   * @param logoHtml logoHtml or {@code null} for none
   */
  public Site setLogoHtml(java.lang.String logoHtml) {
    this.logoHtml = logoHtml;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoImage() {
    return logoImage;
  }

  /**
   * @param logoImage logoImage or {@code null} for none
   */
  public Site setLogoImage(java.lang.String logoImage) {
    this.logoImage = logoImage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLookAndFeel() {
    return lookAndFeel;
  }

  /**
   * @param lookAndFeel lookAndFeel or {@code null} for none
   */
  public Site setLookAndFeel(java.lang.String lookAndFeel) {
    this.lookAndFeel = lookAndFeel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Site setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRevision() {
    return revision;
  }

  /**
   * @param revision revision or {@code null} for none
   */
  public Site setRevision(java.lang.String revision) {
    this.revision = revision;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRevisionHistoryEnabled() {
    return revisionHistoryEnabled;
  }

  /**
   * @param revisionHistoryEnabled revisionHistoryEnabled or {@code null} for none
   */
  public Site setRevisionHistoryEnabled(java.lang.String revisionHistoryEnabled) {
    this.revisionHistoryEnabled = revisionHistoryEnabled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSiteFooter() {
    return siteFooter;
  }

  /**
   * @param siteFooter siteFooter or {@code null} for none
   */
  public Site setSiteFooter(java.lang.String siteFooter) {
    this.siteFooter = siteFooter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSiteName() {
    return siteName;
  }

  /**
   * @param siteName siteName or {@code null} for none
   */
  public Site setSiteName(java.lang.String siteName) {
    this.siteName = siteName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Style getStyle() {
    return style;
  }

  /**
   * @param style style or {@code null} for none
   */
  public Site setStyle(Style style) {
    this.style = style;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTag() {
    return tag;
  }

  /**
   * @param tag tag or {@code null} for none
   */
  public Site setTag(java.lang.String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTheme() {
    return theme;
  }

  /**
   * @param theme theme or {@code null} for none
   */
  public Site setTheme(java.lang.String theme) {
    this.theme = theme;
    return this;
  }

  @Override
  public Site set(String fieldName, Object value) {
    return (Site) super.set(fieldName, value);
  }

  @Override
  public Site clone() {
    return (Site) super.clone();
  }

}
