/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-21 at 06:10:56 UTC 
 * Modify at your own risk.
 */

package com.urlisit.siteswrapper.cloud.model.styleendpoint;

/**
 * Service definition for Styleendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StyleendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Styleendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the styleendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://siteswrapper.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "styleendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Styleendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Styleendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStyle".
   *
   * This request holds the parameters needed by the styleendpoint server.  After setting any optional
   * parameters, call the {@link GetStyle#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetStyle getStyle(java.lang.String id) throws java.io.IOException {
    GetStyle result = new GetStyle(id);
    initialize(result);
    return result;
  }

  public class GetStyle extends StyleendpointRequest<com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style> {

    private static final String REST_PATH = "style/{id}";

    /**
     * Create a request for the method "getStyle".
     *
     * This request holds the parameters needed by the the styleendpoint server.  After setting any
     * optional parameters, call the {@link GetStyle#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetStyle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStyle(java.lang.String id) {
      super(Styleendpoint.this, "GET", REST_PATH, null, com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStyle setAlt(java.lang.String alt) {
      return (GetStyle) super.setAlt(alt);
    }

    @Override
    public GetStyle setFields(java.lang.String fields) {
      return (GetStyle) super.setFields(fields);
    }

    @Override
    public GetStyle setKey(java.lang.String key) {
      return (GetStyle) super.setKey(key);
    }

    @Override
    public GetStyle setOauthToken(java.lang.String oauthToken) {
      return (GetStyle) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStyle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStyle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStyle setQuotaUser(java.lang.String quotaUser) {
      return (GetStyle) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStyle setUserIp(java.lang.String userIp) {
      return (GetStyle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetStyle setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStyle set(String parameterName, Object value) {
      return (GetStyle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStyle".
   *
   * This request holds the parameters needed by the styleendpoint server.  After setting any optional
   * parameters, call the {@link InsertStyle#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style}
   * @return the request
   */
  public InsertStyle insertStyle(com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style content) throws java.io.IOException {
    InsertStyle result = new InsertStyle(content);
    initialize(result);
    return result;
  }

  public class InsertStyle extends StyleendpointRequest<com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style> {

    private static final String REST_PATH = "style";

    /**
     * Create a request for the method "insertStyle".
     *
     * This request holds the parameters needed by the the styleendpoint server.  After setting any
     * optional parameters, call the {@link InsertStyle#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertStyle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style}
     * @since 1.13
     */
    protected InsertStyle(com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style content) {
      super(Styleendpoint.this, "POST", REST_PATH, content, com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style.class);
    }

    @Override
    public InsertStyle setAlt(java.lang.String alt) {
      return (InsertStyle) super.setAlt(alt);
    }

    @Override
    public InsertStyle setFields(java.lang.String fields) {
      return (InsertStyle) super.setFields(fields);
    }

    @Override
    public InsertStyle setKey(java.lang.String key) {
      return (InsertStyle) super.setKey(key);
    }

    @Override
    public InsertStyle setOauthToken(java.lang.String oauthToken) {
      return (InsertStyle) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStyle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStyle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStyle setQuotaUser(java.lang.String quotaUser) {
      return (InsertStyle) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStyle setUserIp(java.lang.String userIp) {
      return (InsertStyle) super.setUserIp(userIp);
    }

    @Override
    public InsertStyle set(String parameterName, Object value) {
      return (InsertStyle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStyle".
   *
   * This request holds the parameters needed by the styleendpoint server.  After setting any optional
   * parameters, call the {@link ListStyle#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListStyle listStyle() throws java.io.IOException {
    ListStyle result = new ListStyle();
    initialize(result);
    return result;
  }

  public class ListStyle extends StyleendpointRequest<com.urlisit.siteswrapper.cloud.model.styleendpoint.model.CollectionResponseStyle> {

    private static final String REST_PATH = "style";

    /**
     * Create a request for the method "listStyle".
     *
     * This request holds the parameters needed by the the styleendpoint server.  After setting any
     * optional parameters, call the {@link ListStyle#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListStyle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStyle() {
      super(Styleendpoint.this, "GET", REST_PATH, null, com.urlisit.siteswrapper.cloud.model.styleendpoint.model.CollectionResponseStyle.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStyle setAlt(java.lang.String alt) {
      return (ListStyle) super.setAlt(alt);
    }

    @Override
    public ListStyle setFields(java.lang.String fields) {
      return (ListStyle) super.setFields(fields);
    }

    @Override
    public ListStyle setKey(java.lang.String key) {
      return (ListStyle) super.setKey(key);
    }

    @Override
    public ListStyle setOauthToken(java.lang.String oauthToken) {
      return (ListStyle) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStyle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStyle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStyle setQuotaUser(java.lang.String quotaUser) {
      return (ListStyle) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStyle setUserIp(java.lang.String userIp) {
      return (ListStyle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStyle setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStyle setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStyle set(String parameterName, Object value) {
      return (ListStyle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStyle".
   *
   * This request holds the parameters needed by the styleendpoint server.  After setting any optional
   * parameters, call the {@link RemoveStyle#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStyle removeStyle(java.lang.String id) throws java.io.IOException {
    RemoveStyle result = new RemoveStyle(id);
    initialize(result);
    return result;
  }

  public class RemoveStyle extends StyleendpointRequest<Void> {

    private static final String REST_PATH = "style/{id}";

    /**
     * Create a request for the method "removeStyle".
     *
     * This request holds the parameters needed by the the styleendpoint server.  After setting any
     * optional parameters, call the {@link RemoveStyle#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveStyle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStyle(java.lang.String id) {
      super(Styleendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStyle setAlt(java.lang.String alt) {
      return (RemoveStyle) super.setAlt(alt);
    }

    @Override
    public RemoveStyle setFields(java.lang.String fields) {
      return (RemoveStyle) super.setFields(fields);
    }

    @Override
    public RemoveStyle setKey(java.lang.String key) {
      return (RemoveStyle) super.setKey(key);
    }

    @Override
    public RemoveStyle setOauthToken(java.lang.String oauthToken) {
      return (RemoveStyle) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStyle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStyle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStyle setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStyle) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStyle setUserIp(java.lang.String userIp) {
      return (RemoveStyle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveStyle setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStyle set(String parameterName, Object value) {
      return (RemoveStyle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStyle".
   *
   * This request holds the parameters needed by the styleendpoint server.  After setting any optional
   * parameters, call the {@link UpdateStyle#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style}
   * @return the request
   */
  public UpdateStyle updateStyle(com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style content) throws java.io.IOException {
    UpdateStyle result = new UpdateStyle(content);
    initialize(result);
    return result;
  }

  public class UpdateStyle extends StyleendpointRequest<com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style> {

    private static final String REST_PATH = "style";

    /**
     * Create a request for the method "updateStyle".
     *
     * This request holds the parameters needed by the the styleendpoint server.  After setting any
     * optional parameters, call the {@link UpdateStyle#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateStyle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style}
     * @since 1.13
     */
    protected UpdateStyle(com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style content) {
      super(Styleendpoint.this, "PUT", REST_PATH, content, com.urlisit.siteswrapper.cloud.model.styleendpoint.model.Style.class);
    }

    @Override
    public UpdateStyle setAlt(java.lang.String alt) {
      return (UpdateStyle) super.setAlt(alt);
    }

    @Override
    public UpdateStyle setFields(java.lang.String fields) {
      return (UpdateStyle) super.setFields(fields);
    }

    @Override
    public UpdateStyle setKey(java.lang.String key) {
      return (UpdateStyle) super.setKey(key);
    }

    @Override
    public UpdateStyle setOauthToken(java.lang.String oauthToken) {
      return (UpdateStyle) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStyle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStyle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStyle setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStyle) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStyle setUserIp(java.lang.String userIp) {
      return (UpdateStyle) super.setUserIp(userIp);
    }

    @Override
    public UpdateStyle set(String parameterName, Object value) {
      return (UpdateStyle) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Styleendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Styleendpoint}. */
    @Override
    public Styleendpoint build() {
      return new Styleendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StyleendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStyleendpointRequestInitializer(
        StyleendpointRequestInitializer styleendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(styleendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
